-- Creación de Schema
DROP SCHEMA IF EXISTS SUPPLY;
CREATE SCHEMA IF NOT EXISTS SUPPLY;
USE SUPPLY;

-- Creación de tablas
CREATE TABLE PRODUCTOS (
ID_PRODUCTO INT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(200) NOT NULL,
PRECIO_UNIDAD INT,
PROVEEDOR VARCHAR(10) NOT NULL,
PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE CLIENTES (
ID_CLIENTE INT,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(10) NOT NULL,
REGDATE DATE,
primary key (ID_CLIENTE)
);

CREATE TABLE TRANSPORTES (
ID_TRANSPORTE INT,
TIPO_U VARCHAR(20) NOT NULL,
CAPACIDAD INT,
UBICACION VARCHAR(50) NOT NULL,
ID_CONDUCTOR INT,
PRIMARY KEY (ID_TRANSPORTE)
);

CREATE TABLE ORDENES (
ID_ORDEN INT,
ID_PRODUCTO INT,
ID_CLIENTE INT,
ID_TRANSPORTE INT,
CANTIDAD INT,
PRECIO_TOTAL INT,
PRIMARY KEY (ID_ORDEN),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FOREIGN KEY (ID_TRANSPORTE) REFERENCES TRANSPORTES(ID_TRANSPORTE)
);

-- Inserción de datos en tablas
INSERT INTO `CLIENTES` (`ID_CLIENTE`,`NOMBRE`,`DIRECCION`,`EMAIL`,`TELEFONO`,`REGDATE`) VALUES (1,'GERARDO MACIAS','SAN MATEO 55, SANTO DOMINGO, 02160','GMACIAS@GMAIL.COM','5512434563','2023-05-30');
INSERT INTO `CLIENTES` (`ID_CLIENTE`,`NOMBRE`,`DIRECCION`,`EMAIL`,`TELEFONO`,`REGDATE`) VALUES (2,'ALEJANDRO ROCHA','FRESNOS 54, VALLE DORADO, 52902','AROCHA@GMAIL.COM','5565781555','2023-05-30');
INSERT INTO `CLIENTES` (`ID_CLIENTE`,`NOMBRE`,`DIRECCION`,`EMAIL`,`TELEFONO`,`REGDATE`) VALUES (3,'HECTOR JUAREZ','SOL 18, GUERRERO, 06300','HJUAREZ@GMAIL.COM','5596215596','2023-05-30');
INSERT INTO `CLIENTES` (`ID_CLIENTE`,`NOMBRE`,`DIRECCION`,`EMAIL`,`TELEFONO`,`REGDATE`) VALUES (4,'ANA OROZCO','SAN ANTONIO 28, DOCTORES, 06720','AOROZCO@GMAIL.COM','5556460926','2023-05-30');
INSERT INTO `CLIENTES` (`ID_CLIENTE`,`NOMBRE`,`DIRECCION`,`EMAIL`,`TELEFONO`,`REGDATE`) VALUES (5,'JAIR FERNANDEZ','JOSE MARIA 91, NAVARTE, 03020','JFERNANDEZ@GMAIL.COM','5519215894','2023-05-30');
INSERT INTO `CLIENTES` (`ID_CLIENTE`,`NOMBRE`,`DIRECCION`,`EMAIL`,`TELEFONO`,`REGDATE`) VALUES (6,'DIEGO HERNANDEZ','PILARES 123, DEL VALLE, 03100','DHERNANDEZ@GMAIL.COM','5520425062','2023-05-30');
INSERT INTO `CLIENTES` (`ID_CLIENTE`,`NOMBRE`,`DIRECCION`,`EMAIL`,`TELEFONO`,`REGDATE`) VALUES (7,'DIANA PEREZ','BERLIN 185, DEL CARMEN,04100','DPEREZ@GMAIL.COM','5548843707','2023-05-30');
INSERT INTO `CLIENTES` (`ID_CLIENTE`,`NOMBRE`,`DIRECCION`,`EMAIL`,`TELEFONO`,`REGDATE`) VALUES (8,'ERNESTO FLORES','LUCAS 11, SANTO TOMAS, 02020','EFLORES@GMAIL.COM','5556672266','2023-05-30');


INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (1,'Balon Futbol','Rojo Azul',600,'MEXIEMSPOR');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (2,'Pelota tenis','Verde',100,'CHSUNITYDE');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (3,'Balon Basket','Negro Azul',700,'CHSUNITYDE');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (4,'Balon Volley','Blanco',400,'MEXIEMSPOR');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (5,'Balon Basket','Naranja',700,'MEXIEMSPOR');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (6,'Balon Futbol','Blanco Negro',600,'MEXIEMSPOR');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (7,'Balon Futbol','Verde Blanco',600,'MEXIEMSPOR');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (8,'Balon Futbol','Rojo Negro',600,'CHSUNITYDE');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (9,'Balon Futbol','Azul',600,'CHSUNITYDE');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (10,'Guantes Futbol','Naranja',350,'CHSUNITYDE');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (11,'Guantes Futbol','Negro',350,'MEXIEMSPOR');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (12,'Guantes Futbol','Verde',350,'MEXIEMSPOR');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (13,'Gorra Tenis','Azul',250,'MEXIEMSPOR');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (14,'Gorra Tenis','Blanco',250,'CHSUNITYDE');
INSERT INTO `PRODUCTOS` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (15,'Gorra Tenis','Rosa',300,'CHSUNITYDE');

-- Creación de vistas

CREATE VIEW clientes_email AS
SELECT NOMBRE, EMAIL
FROM clientes;

CREATE VIEW productos_precio AS
SELECT NOMBRE, DESCRIPCION, PRECIO_UNIDAD
FROM productos;

CREATE VIEW productos_proveedor AS
SELECT NOMBRE, DESCRIPCION, PROVEEDOR
FROM productos;

CREATE VIEW clientes_direccion AS
SELECT NOMBRE, DIRECCION
FROM clientes;

CREATE VIEW clientes_contacto AS
SELECT NOMBRE, DIRECCION, EMAIL, TELEFONO
FROM clientes;

SELECT * FROM productos_precio
WHERE PRECIO_UNIDAD >= 400;

SELECT * FROM productos_proveedor
WHERE PROVEEDOR = 'CHSUNITYDE';

SELECT * FROM clientes_direccion
WHERE DIRECCION LIKE '%DEL VALLE%';

SELECT * FROM clientes_contacto
WHERE EMAIL LIKE '%GMAIL%';

-- Uso de funciones

SELECT COUNT(NOMBRE) AS n_nombres
FROM CLIENTES;

SELECT LOWER(EMAIL) AS c_email
FROM CLIENTES;

DROP FUNCTION IF EXISTS fn_ver_email;

DELIMITER $$
CREATE FUNCTION fn_ver_email (f_id_cliente INT)

RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
DECLARE client_mail VARCHAR(50);
SET client_mail =
	(SELECT EMAIL AS CLIENTE_MAIL FROM CLIENTES WHERE ID_CLIENTE = f_id_cliente);
    
    RETURN client_mail;
END $$
DELIMITER ;

SELECT fn_ver_email (5);