DROP SCHEMA IF EXISTS SUPPLY;
CREATE SCHEMA IF NOT EXISTS SUPPLY;
USE SUPPLY;

CREATE TABLE PRODUCTOS (
ID_PRODUCTO INT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(200) NOT NULL,
PRECIO_UNIDAD INT,
PROVEEDOR VARCHAR(10) NOT NULL,
PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE CLIENTES (
ID_CLIENTE INT,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(10) NOT NULL,
REGDATE DATE,
primary key (ID_CLIENTE)
);

CREATE TABLE TRANSPORTES (
ID_TRANSPORTE INT,
TIPO_U VARCHAR(20) NOT NULL,
CAPACIDAD INT,
UBICACION VARCHAR(50) NOT NULL,
ID_CONDUCTOR INT,
PRIMARY KEY (ID_TRANSPORTE)
);

CREATE TABLE ORDENES (
ID_ORDEN INT,
ID_PRODUCTO INT,
ID_CLIENTE INT,
ID_TRANSPORTE INT,
CANTIDAD INT,
PRECIO_TOTAL INT,
PRIMARY KEY (ID_ORDEN),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
FOREIGN KEY (ID_TRANSPORTE) REFERENCES TRANSPORTES(ID_TRANSPORTE)
);