/*
-- Query: SELECT * FROM supply.productos
LIMIT 0, 1000

-- Date: 2023-06-08 23:32
*/
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (1,'Balon Futbol','Rojo Azul',600,'MEXIEMSPOR');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (2,'Pelota tenis','Verde',100,'CHSUNITYDE');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (3,'Balon Basket','Negro Azul',700,'CHSUNITYDE');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (4,'Balon Volley','Blanco',400,'MEXIEMSPOR');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (5,'Balon Basket','Naranja',700,'MEXIEMSPOR');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (6,'Balon Futbol','Blanco Negro',600,'MEXIEMSPOR');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (7,'Balon Futbol','Verde Blanco',600,'MEXIEMSPOR');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (8,'Balon Futbol','Rojo Negro',600,'CHSUNITYDE');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (9,'Balon Futbol','Azul',600,'CHSUNITYDE');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (10,'Guantes Futbol','Naranja',350,'CHSUNITYDE');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (11,'Guantes Futbol','Negro',350,'MEXIEMSPOR');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (12,'Guantes Futbol','Verde',350,'MEXIEMSPOR');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (13,'Gorra Tenis','Azul',250,'MEXIEMSPOR');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (14,'Gorra Tenis','Blanco',250,'CHSUNITYDE');
INSERT INTO `` (`ID_PRODUCTO`,`NOMBRE`,`DESCRIPCION`,`PRECIO_UNIDAD`,`PROVEEDOR`) VALUES (15,'Gorra Tenis','Rosa',300,'CHSUNITYDE');
