-- Sentencias de sublenguaje de Control de Transacciones (TCL)

-- PRIMERA TABLA - ELIMINACIÓN DE REGISTROS, ROLLBACK Y COMMIT

-- Comprobación de datos de la tabla
SELECT * FROM TRANSPORTES;

-- Autocommit Status
SELECT @@AUTOCOMMIT;
SET AUTOCOMMIT = 0;

START TRANSACTION;
-- Eliminación de registros de la tabla "TRANSPORTES"
DELETE FROM TRANSPORTES
WHERE ID_TRANSPORTE = 3;
DELETE FROM TRANSPORTES
WHERE ID_TRANSPORTE = 4;

-- ROLLBACK;
COMMIT;


-- SEGUNDA TABLA - INSERCIÓN DE REGISTROS, SAVEPOINT Y ROLLBACK TO

-- Comprobar datos
SELECT * FROM ORDENES;

-- Autocommit Status
SELECT @@AUTOCOMMIT;
SET AUTOCOMMIT = 0;

START TRANSACTION;

-- Inserción de registro en tabla "ORDENES"
INSERT INTO `ORDENES` (`ID_PRODUCTO`,`ID_CLIENTE`,`ID_TRANSPORTE`,`CANTIDAD`,`PRECIO_TOTAL`,`FECHA`) VALUES (1,6,1,1,600,'2023-07-02');
INSERT INTO `ORDENES` (`ID_PRODUCTO`,`ID_CLIENTE`,`ID_TRANSPORTE`,`CANTIDAD`,`PRECIO_TOTAL`,`FECHA`) VALUES (1,6,1,1,600,'2023-07-02');
INSERT INTO `ORDENES` (`ID_PRODUCTO`,`ID_CLIENTE`,`ID_TRANSPORTE`,`CANTIDAD`,`PRECIO_TOTAL`,`FECHA`) VALUES (1,6,1,1,600,'2023-07-02');
INSERT INTO `ORDENES` (`ID_PRODUCTO`,`ID_CLIENTE`,`ID_TRANSPORTE`,`CANTIDAD`,`PRECIO_TOTAL`,`FECHA`) VALUES (1,6,1,1,600,'2023-07-02');
SAVEPOINT SP1;

INSERT INTO `ORDENES` (`ID_PRODUCTO`,`ID_CLIENTE`,`ID_TRANSPORTE`,`CANTIDAD`,`PRECIO_TOTAL`,`FECHA`) VALUES (4,6,1,1,400,'2023-07-04');
INSERT INTO `ORDENES` (`ID_PRODUCTO`,`ID_CLIENTE`,`ID_TRANSPORTE`,`CANTIDAD`,`PRECIO_TOTAL`,`FECHA`) VALUES (4,6,1,1,400,'2023-07-04');
INSERT INTO `ORDENES` (`ID_PRODUCTO`,`ID_CLIENTE`,`ID_TRANSPORTE`,`CANTIDAD`,`PRECIO_TOTAL`,`FECHA`) VALUES (4,6,1,1,400,'2023-07-04');
INSERT INTO `ORDENES` (`ID_PRODUCTO`,`ID_CLIENTE`,`ID_TRANSPORTE`,`CANTIDAD`,`PRECIO_TOTAL`,`FECHA`) VALUES (4,6,1,1,400,'2023-07-04');
SAVEPOINT SP2;

-- ROLLBACK TO SP1;
COMMIT;