/*
-- Query: SELECT * FROM supply.transportes
LIMIT 0, 1000

-- Date: 2023-06-19 23:57
*/
INSERT INTO `` (`ID_TRANSPORTE`,`TIPO_U`,`CAPACIDAD`,`UBICACION`,`ID_CONDUCTOR`) VALUES (1,'CAMION',3,'CDX',11);
INSERT INTO `` (`ID_TRANSPORTE`,`TIPO_U`,`CAPACIDAD`,`UBICACION`,`ID_CONDUCTOR`) VALUES (2,'FURGONETA',2,'TLZ',14);
INSERT INTO `` (`ID_TRANSPORTE`,`TIPO_U`,`CAPACIDAD`,`UBICACION`,`ID_CONDUCTOR`) VALUES (3,'CAMION',5,'TIZ',16);
INSERT INTO `` (`ID_TRANSPORTE`,`TIPO_U`,`CAPACIDAD`,`UBICACION`,`ID_CONDUCTOR`) VALUES (4,'CAMION',6,'TLZ',19);
INSERT INTO `` (`ID_TRANSPORTE`,`TIPO_U`,`CAPACIDAD`,`UBICACION`,`ID_CONDUCTOR`) VALUES (5,'REMOLQUE',10,'CDX',22);
